# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'GFPS.Global.Digital.ConnectedSolutions.Dev(07139530-8c10-4c8d-b39e-2254751032ee)'
    appType: 'webApp'
    WebAppName: 'WebappVictorTest'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'